config/routes.rb
Rails.application.routes.draw do
  resources :measurements

  resources :users do
    resources :activities
  end
  resources :strength_activities
  resources :fitness_activities

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: :delete

  root to: 'static_pages#home'
  match '/help',    to: 'static_pages#help' , via: 'get'
  match '/about',   to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  get 'users/index'
  get 'users/show'
  get 'users/new'

  match 'destroy_activity', to: 'activities#destroy', via: :delete

  match 'fitness_activity/new', to: 'fitness_activities#new', via:'get'
  match 'strength_activity/new', to: 'strength_activities#new', via:'get'
  match 'measurement/new', to: 'measurements#new', via:'get'

  match 'follow_user', to: 'users#follow', via: 'get'
  match 'unfollow_user', to: 'users#unfollow', via: 'get'

  match 'cardio_report', to: 'reports#cardio', via: 'get'
  match 'strength_report', to: 'reports#strength', via: 'get'
  match 'weight_report', to: 'reports#weight', via: 'get'

  match '/signup', to: 'users#new', via: 'get'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if current_user
      @followed = current_user.following.entries
      @followed << current_user
      @feed = Activity.desc(:created_at).where(:user.in => @followed).limit(20)
    end
  end

  def help
  end

  def about

  end

  def contact

  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About us') %>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact us') %>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>

<% if current_user %>
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-8 pull-left">
          <% if @feed %>
              <% for activity in @feed %>
                  <p><%= render activity %></p>
              <% end %>
          <% else %>
              <div class="jumbotron">
                <h1>Add activity or follow a user to get your feed</h1>
                <%= link_to 'Sign up now!', signup_path, class: 'btn btn-large btn-primary' %>
              </div>
          <% end %>
        </div>


        <div class="col-xs-3 pull-right">
          <div class="panel-body  sidebar">
            <% for user in User.all %>
                <% unless current_user == user %>

                    <div class="well-sm">
                      <strong><%= link_to "#{user.first_name} #{user.last_name}", user_path(user) %></strong>

                      <div class="pull-right">
                        <% if @followed.include?(user) %>
                            <%= link_to 'unfollow', unfollow_user_path(user), :class => 'btn btn-xs btn-danger' %>
                        <% else %>
                            <%= link_to 'follow', follow_user_path(user), :class => 'btn  btn-xs btn-success' %>
                        <% end %>
                      </div>
                    </div>

                <% end %>
                <div class="divider"></div>
            <% end %>
          </div>
        </div>
      </div>
<% else %>
    <div class="jumbotron">
      <h1>Sign up now</h1>
      <%= link_to 'Sign up now!', signup_path, class: 'btn btn-large btn-primary' %>
    </div>

    </div>
<% end %>