config/routes.rb
Rails.application.routes.draw do
  resources :measurements

  resources :users do
    resources :activities
  end
  resources :strength_activities
  resources :fitness_activities

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: :delete

  root to: 'static_pages#home'
  match '/help',    to: 'static_pages#help' , via: 'get'
  match '/about',   to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  get 'users/index'
  get 'users/show'
  get 'users/new'

  match 'destroy_activity', to: 'activities#destroy', via: :delete

  match 'fitness_activity/new', to: 'fitness_activities#new', via:'get'
  match 'strength_activity/new', to: 'strength_activities#new', via:'get'
  match 'measurement/new', to: 'measurements#new', via:'get'

  match 'follow_user', to: 'users#follow', via: 'get'
  match 'unfollow_user', to: 'users#unfollow', via: 'get'

  match 'cardio_report', to: 'reports#cardio', via: 'get'
  match 'strength_report', to: 'reports#strength', via: 'get'
  match 'weight_report', to: 'reports#weight', via: 'get'

  match '/signup', to: 'users#new', via: 'get'

end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  include ActiveModel::SecurePassword
  include Mongoid::Paperclip

  field :first_name, type: String
  field :last_name, type: String
  field :email, type: String
  field :gender, type: String
  field :athlete_type, type: String
  field :date_of_birth, type: Date
  field :password_digest, type: String
  field :remember_token, type: String
  has_secure_password

  has_mongoid_attached_file :photo, :default_url => "silhouette.jpg"
  validates_attachment :photo, content_type: { content_type: ['image/jpg', 'image/jpeg','image/png', 'image/gif'] }

  has_many :activities, dependent: :destroy
  has_and_belongs_to_many :following, class_name: 'User', inverse_of: :followers, autosave: true
  has_and_belongs_to_many :followers, class_name: 'User', inverse_of: :following



  validates :password, presence: true, length: {minimum: 6}
  validates :password_confirmation, presence: true

  validates :first_name, :last_name, presence: true, length: {in: 2..30}

  GENDERS = ['Male', 'Female']
  validates :gender, inclusion: GENDERS

  ATHLETE_TYPES = ['Runner', 'Cyclist', 'Powerlifter']
  validates :athlete_type, inclusion: ATHLETE_TYPES

  # turned off for dev stage
  # validates_date :date_of_birth
  # validates :email, presence: true, :email_format => {:message => 'invalid email'}

  validates :email, presence: true, uniqueness: {message: 'duplicate email'}

  index({email: 1}, {unique: true})
  index({remember_token: 1})

  before_save do |user|
    user.email = email.downcase
    user.remember_token = SecureRandom.urlsafe_base64
  end

  def follow!(other_user)
    if self.id != other_user.id && !self.following.include?(other_user)
      self.following << other_user
      true
    else
      false
    end
  end

  def unfollow!(other_user)
    if self.following.delete(other_user)
      true
    else
      false
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user_activities = Activity.desc(:created_at).where(user: params[:id])
    puts
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        sign_in @user
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        sign_in @user
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def follow
    other_user = User.find_by(id: params[:format])
    if current_user.follow!(other_user)
      redirect_to root_path, :flash => {notice: "Followed #{other_user.first_name} #{other_user.last_name}"}
    else
      redirect_to root_path, :flash => {notice: "something went wrong"}
    end
  end

  def unfollow
    other_user = User.find_by(id: params[:format])
    if current_user.unfollow!(other_user)
      redirect_to root_path, :flash => {:notice => "Unfollowed #{other_user.first_name} #{other_user.last_name}"}
    else
      redirect_to root_path, :flash => {:notice => "something went wrong"}
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:first_name,
                                 :last_name,
                                 :date_of_birth,
                                 :email,
                                 :gender,
                                 :athlete_type,
                                 :password,
                                 :password_confirmation,
                                 :photo)
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_form.html.erb
<%= form_for @user, :html => {:class => "form-horizontal user"} do |f| %>

    <% if @user.errors.any? %>
        <div id="error_expl" class="panel panel-danger">
          <div class="panel-heading">
            <h3 class="panel-title"><%= pluralize(@user.errors.count, "error") %> prohibited this user from being
              saved:</h3>
          </div>
          <div class="panel-body">
            <ul>
              <% @user.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :photo, :class => 'control-label col-lg-2' %>
      <div class="col-lg-5">
        <%= f.file_field :photo, :class => 'form-control' %>
      </div>
      <%= f.error_span(:first_name) %>
    </div>

    <div class="form-group">
      <%= f.label :first_name, :class => 'control-label col-lg-2' %>
      <div class="col-lg-5">
        <%= f.text_field :first_name, :class => 'form-control' %>
      </div>
      <%= f.error_span(:first_name) %>
    </div>
    <div class="form-group">
      <%= f.label :last_name, :class => 'control-label col-lg-2' %>
      <div class="col-lg-5">
        <%= f.text_field :last_name, :class => 'form-control' %>
      </div>
      <%= f.error_span(:last_name) %>
    </div>
    <div class="form-group">
      <%= f.label :email, :class => 'control-label col-lg-2' %>
      <div class="col-lg-5">
        <%= f.text_field :email, :class => 'form-control' %>
      </div>
      <%= f.error_span(:email) %>
    </div>
    <div class="form-group">
      <%= f.label :gender, :class => 'control-label col-lg-2' %>
      <div class="col-lg-5">
        <%= f.select :gender, User::GENDERS, :class => 'form-control' %>
      </div>
      <%= f.error_span(:gender) %>
    </div>
    <div class="form-group">
      <%= f.label :athlete_type, :class => 'control-label col-lg-2' %>
      <div class="col-lg-5">
        <%= f.select :athlete_type, User::ATHLETE_TYPES, :class => 'form-control' %>
      </div>
      <%= f.error_span(:athlete_type) %>
    </div>
    <div class="form-group">
      <%= f.label :date_of_birth, :class => 'control-label col-lg-2' %>
      <div class="col-lg-5">
        <%= date_field(:user, :date_of_birth)%>
      </div>
      <%= f.error_span(:date_of_birth) %>
    </div>
    <div class="form-group">
      <%= f.label :password, :class => 'control-label col-lg-2' %>
      <div class="col-lg-5">
        <%= f.password_field :password, :value=> '123456', :class => 'form-control'  %>
      </div>
      <%= f.error_span(:password) %>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation, :class => 'control-label col-lg-2' %>
      <div class="col-lg-5">
        <%= f.password_field :password_confirmation,:value=> '123456', :class => 'form-control' %>
      </div>
      <%= f.error_span(:password) %>
    </div>

    <div class="form-group">
      <div class="col-lg-offset-2 col-lg-5">
        <%= f.submit nil, :class => 'btn btn-primary' %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                    users_path, :class => 'btn btn-default' %>
      </div>
    </div>

<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:first_name) %></th>
      <th><%= model_class.human_attribute_name(:last_name) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:gender) %></th>
      <th><%= model_class.human_attribute_name(:athlete_type) %></th>
      <th><%= model_class.human_attribute_name(:date_of_birth) %></th>
      <th><%= model_class.human_attribute_name(:password_digest) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.gender %></td>
        <td><%= user.athlete_type %></td>
        <td><%= user.date_of_birth %></td>
        <td><%= user.password_digest %></td>
        <td><%=l user.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<div class="page-header">
  <h1>Sign up</h1>
</div>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<div class="container-fluid">
  <div class="row ">
    <%= image_tag @user.photo, class: 'img-thumbnail col-xs-2' %>

    <div class="important col-xs-5 pull-right text-right">
      <h1><%= "#{@user.first_name} #{@user.last_name}" %></h1>

      <p>Active since <%= @user.created_at.strftime("%B %Y") %></p>
      <% if current_user == @user %>
          <div class="well pull-right text-right">
            <strong>NEW:</strong>
            <div class="btn-group" role="group">
              <%= link_to 'fitness', fitness_activity_new_path, class: 'btn btn-large btn-success' %>
              <%= link_to 'strength', strength_activity_new_path, class: 'btn btn-large btn-success' %>
              <%= link_to 'measurement', measurement_new_path, class: 'btn btn- btn-success' %>
            </div>
            <br>
            <strong>View all:</strong>
            <div class="btn-group" role="group">
              <%= link_to 'fitness', fitness_activities_path(:id => current_user[:id]), class: 'btn btn-large btn-info' %>
              <%= link_to 'strength', strength_activities_path(:id => current_user[:id]), class: 'btn btn-large btn-info' %>
              <%= link_to 'measurement', measurements_path(:id => current_user[:id]), class: 'btn btn- btn-info' %>
            </div>
          </div>


      <% end %>
    </div>

  </div>
  <div class="row">
    <div class="col-xs-6">
      <% if @user_activities.any? %>
          <h3>Activities (<%= @user_activities.count %>)</h3>

          <% for activity in @user_activities %>
              <p><%= render activity %></p>
          <% end %>
      <% end %>
    </div>
  </div>


  <%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn btn-default' %>

  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))},
              :class => 'btn btn-danger' %>
</div>