config/routes.rb
Rails.application.routes.draw do
  resources :measurements

  resources :users do
    resources :activities
  end
  resources :strength_activities
  resources :fitness_activities

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: :delete

  root to: 'static_pages#home'
  match '/help',    to: 'static_pages#help' , via: 'get'
  match '/about',   to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  get 'users/index'
  get 'users/show'
  get 'users/new'

  match 'destroy_activity', to: 'activities#destroy', via: :delete

  match 'fitness_activity/new', to: 'fitness_activities#new', via:'get'
  match 'strength_activity/new', to: 'strength_activities#new', via:'get'
  match 'measurement/new', to: 'measurements#new', via:'get'

  match 'follow_user', to: 'users#follow', via: 'get'
  match 'unfollow_user', to: 'users#unfollow', via: 'get'

  match 'cardio_report', to: 'reports#cardio', via: 'get'
  match 'strength_report', to: 'reports#strength', via: 'get'
  match 'weight_report', to: 'reports#weight', via: 'get'

  match '/signup', to: 'users#new', via: 'get'

end

app/models/activity.rb
class Activity
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paperclip
  field :note, type: String

  belongs_to :user

  has_mongoid_attached_file :photo
  validates_attachment :photo, content_type: { content_type: ['image/jpg', 'image/jpeg','image/png', 'image/gif'] }
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_filter :signed_in_user, only: [:create, :destroy]
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
    @activity = current_user.activities.find_by(id: params[:format])
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)
    @activity.user = current_user
    current_user.activities.push(@activity)


    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    redirect_to @current_user, notice: 'Activity was successfully destroyed.'


  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = current_user.activities.find_by(id: params[:format])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:note, :photo)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
    <% if @activity.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

          <ul>
            <% @activity.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :note %><br>
      <%= f.text_field :note %>
    </div>

    <div class="field">
      <%= f.label :photo %><br>
      <%= f.file_field :photo %>
    </div>



    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<h1>Listing activities</h1>

<table>
  <thead>
    <tr>
      <th>Note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.note %></td>
        <td><%= link_to 'Show', activity %></td>
        <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
        <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Activity', new_activity_path %>

app/views/activities/new.html.erb
<h1>New activity</h1>

<%= render 'form' %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Note:</strong>
  <%= @activity.note %>
  <%= image_tag @activity.photo %>
</p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>