config/routes.rb
Rails.application.routes.draw do
  resources :measurements

  resources :users do
    resources :activities
  end
  resources :strength_activities
  resources :fitness_activities

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: :delete

  root to: 'static_pages#home'
  match '/help',    to: 'static_pages#help' , via: 'get'
  match '/about',   to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  get 'users/index'
  get 'users/show'
  get 'users/new'

  match 'destroy_activity', to: 'activities#destroy', via: :delete

  match 'fitness_activity/new', to: 'fitness_activities#new', via:'get'
  match 'strength_activity/new', to: 'strength_activities#new', via:'get'
  match 'measurement/new', to: 'measurements#new', via:'get'

  match 'follow_user', to: 'users#follow', via: 'get'
  match 'unfollow_user', to: 'users#unfollow', via: 'get'

  match 'cardio_report', to: 'reports#cardio', via: 'get'
  match 'strength_report', to: 'reports#strength', via: 'get'
  match 'weight_report', to: 'reports#weight', via: 'get'

  match '/signup', to: 'users#new', via: 'get'

end

app/views/layouts/_footer.html.erb
<div class="row">
  <footer class="clearfix footer col-xs-12">
    <small>
      Project2
    </small>
    <nav>
      <ul>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
      </ul>
    </nav>
  </footer>
</div>
<script type="text/javascript">
    $(function () {
        $("tr[data-link]").click(function () {
            window.location = this.dataset.link
        });
    });
</script>

app/views/layouts/_header.html.erb
<%= nav_bar :responsive => :top, :brand => "Project2", :responsive => true do %>
    <%= menu_group do %>
        <%= menu_item "Home", root_path %>
        <% if current_user %>
            <%= menu_item 'User', user_path(current_user[:id]) %>
            <%= drop_down 'Reports' do %>
                <%= menu_item 'Cardio', cardio_report_path(:id => current_user[:id]) %>
                <%= menu_item 'Strength', strength_report_path(:id => current_user[:id]) %>
                <%= menu_item 'Weight', weight_report_path(:id => current_user[:id]) %>
            <% end %>
        <% end %>

        <%= menu_item 'About Us', about_path %>
        <%= menu_item 'Contact', contact_path %>
    <% end %>
    <%= menu_group :pull => :right do %>
        <% if current_user %>
            <%= drop_down "#{current_user.first_name} #{current_user.last_name}" do %>
                <%= menu_item 'Profile', user_path(current_user) %>
                <%= menu_item 'Edit', edit_user_path(:id => current_user[:id]) %>
            <% end %>
            <%= menu_item 'Log Out', signout_path, method: 'delete' %>

        <% else %>
            <%= form_for :session, url: sessions_path, html: {:class => 'navbar-form pull-right'} do |f| -%>
                <p><%= f.text_field :email %>
                  <%= f.password_field :password, value: 123456 %>
                  <%= f.submit 'Sign in' %></p>
            <% end -%>
        <% end %>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project2 | <%= yield(:title) %></title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <%= bootstrap_flash %>

  <%= yield %>
  <%= render 'layouts/footer' %>

</div>
</body>
</html>